apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dstrategies-canary
  namespace: user02-gitops-argocd
spec:
  destination:
    name: ''
    namespace: user02-canary
    server: 'https://kubernetes.default.svc'
  source:
    path: canary
    repoURL: https://github.com/Nar6mes3/dstrategies-app-deployment.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true